JobITs-DSM/Benecia

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/WelfareCode.java, src/main/java/com/jobits/dsm/benecia/recruitment/code/WelfareCode.java
=> #7 복리후생 코드

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/ProgrammingLanguageCode.java
=> #11 필요언어 코드

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/TechnologyCode.java
=> #13 기타기술 코드

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/ScreeningProcessCode.java
=> #14 전형절차 코드 추가

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/BusinessAreaCode.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/BusinessAreaCode.java
=> #20 사업분야 코드

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseEmployeeCountCode.java
=> #21 근로자수 코드

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseDivisionCode.java
=> [ADD] #23 <EnterpriseDivisionCode>

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseEmployeeCountCode.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/ProgrammingLanguageCode.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/RecruitmentFullTimePayCode.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/RecruitmentReportingTimeCode.java, src/main/java/com/jobits/dsm/benecia/global/exception/AttributeConvertFailedException.java
=> 12 정규직전환급여 코드

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/BusinessAreaCode.java
=> #41 <BusinessAreaCode> converter 추가

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseDivisionCode.java
=> #42 <EnterpriseDivisionCode> converter 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/HiringArea.java
=> #43 <HiringArea> converter 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/RecruitmentStatusCode.java
=> #44 <RecruitmentStatusCode> converter 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/ScreeningProcessCode.java
=> #45 <ScreeningProcessCode> converter 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/TechnologyCode.java
=> #46 <TechnologyCode> converter 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/WelfareCode.java
=> #47 WelfareCode converter 추가

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseDivisionCode.java
=> [MODIFY] #34 EnterpriseDivisionCode Converter 추가

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseDivisionCode.java
=> 34 기업구분 Converter 중첩 클래스 추가

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseEmployeeCountCode.java
=> #57 <EnterpriseEmployeeCountCode> converter 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/programminglanguage/ProgrammingLanguage.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/programminglanguage/ProgrammingLanguageRepository.java, src/test/java/com/jobits/dsm/benecia/domain/enterprise/domain/ProgrammingLanguageTest.java
=> #58 패키지명 수정

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/BusinessAreaCode.java
=> #60 <BusinessAreaCode> converter 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/HiringArea.java
=> #63 <HiringArea> converter 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/RecruitmentStatusCode.java
=> #64 <RecruitmentStatusCode> converter 수정

src/main/java/com/jobits/dsm/benecia/domain/enterprise/code/EnterpriseDivisionCode.java
=> #62 <EnterpriseDivisionCode> map 변수명 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/ScreeningProcessCode.java
=> #65 <ScreeningProcessCode> converter 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/TechnologyCode.java
=> #66 <TechnologyCode> converter 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/WelfareCode.java
=> #67 <WelfareCode> converter 추가

src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepository.java
=> Student Enttity / Repository 추가

src/main/java/com/jobits/dsm/benecia/domain/review/code/ReviewCode.java
=> #91 Review Code 추가

src/main/java/com/jobits/dsm/benecia/domain/contract/domain/Contract.java, src/main/java/com/jobits/dsm/benecia/domain/contract/domain/ContractRepository.java, src/test/java/com/jobits/dsm/benecia/domain/contract/ContractRepositoryTest.java
=> 근로계약 Entity 추가

src/main/java/com/jobits/dsm/benecia/domain/training/domain/Training.java, src/main/java/com/jobits/dsm/benecia/domain/training/domain/TrainingRepository.java, src/test/java/com/jobits/dsm/benecia/domain/training/domain/TraningRepositoryTest.java
=> 현장 실습 엔티티 추가

src/main/java/com/jobits/dsm/benecia/domain/review/domain/Review.java, src/main/java/com/jobits/dsm/benecia/domain/review/domain/ReviewRepository.java, src/test/java/com/jobits/dsm/benecia/domain/review/domain/ReviewRepositoryTest.java
=> #90 Review entity 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/code/HiringAreaCode.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/hiringarea/HiringArea.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/hiringarea/HiringAreaRepository.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/HiringRepositoryTest.java
=> #96 채용 분야 엔티티 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/screeningprocess/ScreeningProcess.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/screeningprocess/ScreeningProcessRepository.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/ScreeningProcessRepositoryTest.java
=> #98 전형절차 엔티티 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/welfare/Welfare.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/welfare/WelfareRepository.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/WelfareRepositoryTest.java
=> #101 복리후생 엔티티 추가

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/technology/Technology.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/technology/TechnologyRepository.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/TechnologyRepositoryTest.java
=> #103 technology entity

.github/workflows/CD.yml, Dockerfile, build.gradle
=> 48 Continuous Deploy

src/main/java/com/jobits/dsm/benecia/domain/application/code/ApplicationCode.java
=> #95 Application Code 추가

src/main/java/com/jobits/dsm/benecia/domain/attatchment/domain/Attachment.java, src/main/java/com/jobits/dsm/benecia/domain/attatchment/domain/AttachmentRepository.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java, src/test/java/com/jobits/dsm/benecia/domain/attachment/domain/AttachmentRepositoryTest.java
=> #105 첨부파일 엔티티 추가

build.gradle, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/Recruitment.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentId.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepository.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepository.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryTest.java, src/test/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepositoryTest.java
=> #83 student entity test 추가

build.gradle, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/Recruitment.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentId.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepository.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryTest.java
=> #2 recruitment entity 추가

src/main/java/com/jobits/dsm/benecia/BeneciaApplication.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/Application.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/ApplicationRepository.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java
=> #94 지원 엔티티 추가

src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseCodeController.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/response/CodeResponse.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseCodeService.java, src/main/resources/application.yml
=> 109 근로자수 코드 목록 API

src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseCodeController.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseCodeService.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentCodeController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentCodeService.java, src/main/java/com/jobits/dsm/benecia/global/code/CodeResponse.java
=> #115 필요 언어 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentCodeController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentCodeService.java
=> #117 복리후생 코드 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentCodeController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentCodeService.java
=> #119 모집의뢰 코드 목록 API들

src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/businessarea/BusinessArea.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseCodeController.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseCodeService.java
=> 113 사업분야 코드 목록 API

src/main/java/com/jobits/dsm/benecia/BeneciaApplication.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java, src/main/java/com/jobits/dsm/benecia/global/security/FilterConfig.java, src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java, src/main/java/com/jobits/dsm/benecia/global/security/TokenFilter.java, src/main/java/com/jobits/dsm/benecia/global/security/auth/AuthDetails.java, src/main/java/com/jobits/dsm/benecia/global/security/auth/EnterpriseDetailsService.java, src/main/java/com/jobits/dsm/benecia/global/security/auth/StudentDetailsService.java, src/main/java/com/jobits/dsm/benecia/global/security/auth/UserMarker.java, src/main/java/com/jobits/dsm/benecia/global/security/dto/AccessToken.java, src/main/java/com/jobits/dsm/benecia/global/security/dto/Tokens.java, src/main/java/com/jobits/dsm/benecia/global/security/exceptions/JwtInvalidSignatureException.java, src/main/java/com/jobits/dsm/benecia/global/security/exceptions/JwtTokenExpiredException.java, src/main/java/com/jobits/dsm/benecia/global/security/exceptions/SecurityEnterpriseNotFoundException.java, src/main/java/com/jobits/dsm/benecia/global/security/exceptions/SecurityErrorCode.java, src/main/java/com/jobits/dsm/benecia/global/security/exceptions/SecurityStudentNotFoundException.java, src/main/java/com/jobits/dsm/benecia/global/security/jwt/JwtTokenProvider.java, src/main/java/com/jobits/dsm/benecia/global/security/property/JwtProperty.java, src/main/java/com/jobits/dsm/benecia/global/security/property/JwtRoleProperty.java, src/test/resources/application.yml
=> #78 JwtTokenProvider 추가

build.gradle, src/main/java/com/jobits/dsm/benecia/infrastructure/redis/EmbeddedRedisConfig.java, src/main/java/com/jobits/dsm/benecia/infrastructure/redis/RedisConfig.java, src/main/java/com/jobits/dsm/benecia/infrastructure/redis/RedisProperty.java, src/main/resources/application.yml, src/test/resources/application.yml
=> Redis 설정 추가

src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/businessarea/BusinessArea.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/businessarea/BusinessAreaRepository.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java
=> 127 기업 등록시 사업분야 추가 등록

src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/cache/EnterpriseRefreshToken.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/cache/EnterpriseRefreshTokenRepository.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/exceptions/EnterpriseErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/exceptions/EnterpriseNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseController.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/request/EnterpriseSignInRequest.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/response/EnterpriseTokenResponse.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java, src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
=> #124 기업 로그인 추가

src/main/java/com/jobits/dsm/benecia/global/security/jwt/JwtTokenProvider.java, src/main/java/com/jobits/dsm/benecia/infrastructure/redis/EmbeddedRedisConfig.java, src/main/resources/application.yml
=> Token Builder 에러 수정

src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryCustom.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseController.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/request/ModifyEnterpriseInfoRequest.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java, src/main/java/com/jobits/dsm/benecia/infrastructure/redis/EmbeddedRedisConfig.java, src/test/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseServiceTest.java
Resolved #138 
담당자 전화번호 14자리 맞는지 확인해주세요
=> #138 기업 정보 수정 API

src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java
=> [REFACTOR] #140 패키지명 오타 수정

src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/response/EnterpriseInfoResponse.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentId.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/programminglanguage/ProgrammingLanguage.java, src/main/java/com/jobits/dsm/benecia/infrastructure/querydsl/QuerydslConfig.java
=> 144 refactoring

src/main/java/com/jobits/dsm/benecia/domain/admin/exception/AdminErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/admin/exception/UnauthorizedAdminException.java, src/main/java/com/jobits/dsm/benecia/domain/admin/presentation/AdminController.java, src/main/java/com/jobits/dsm/benecia/domain/admin/presentation/payload/request/AdminLoginRequest.java, src/main/java/com/jobits/dsm/benecia/domain/admin/presentation/payload/response/AdminTokenResponse.java, src/main/java/com/jobits/dsm/benecia/domain/admin/property/AdminProperty.java, src/main/java/com/jobits/dsm/benecia/domain/admin/service/AdminService.java, src/main/java/com/jobits/dsm/benecia/global/security/auth/AdminAuthDetails.java, src/main/java/com/jobits/dsm/benecia/global/security/jwt/JwtTokenProvider.java, src/main/java/com/jobits/dsm/benecia/global/security/property/JwtRoleProperty.java, src/main/resources/application.yml
=> 146 어드민 로그인

src/main/java/com/jobits/dsm/benecia/domain/attachment/exceptions/AttachmentErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/attachment/exceptions/FileSaveFailedException.java, src/main/java/com/jobits/dsm/benecia/domain/attachment/facade/AttachmentFacade.java, src/main/java/com/jobits/dsm/benecia/domain/attachment/presentation/AttachmentController.java, src/main/java/com/jobits/dsm/benecia/domain/attachment/presentation/payload/response/SaveAttachmentResponse.java, src/main/java/com/jobits/dsm/benecia/domain/attachment/service/AttachmentService.java, src/main/resources/application.yml
=> 150 첨부파일 저장

src/main/java/com/jobits/dsm/benecia/domain/attachment/exceptions/AttachmentErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/attachment/exceptions/AttachmentNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/attachment/facade/AttachmentFacade.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/Documentation.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/Form.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/programminglanguage/ProgrammingLanguageRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/screeningprocess/ScreeningProcess.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/facade/RecruitmentFacade.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/CreateRecruitmentRequest.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/ScreeningProcessRepositoryTest.java
=> 123 모집의뢰 등록 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/Recruitment.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/tag/RecruitmentTag.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/tag/RecruitmentTagId.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/tag/RecruitmentTagRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/tag/Tag.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/facade/RecruitmentFacade.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentTagRepositoryTest.java
=> 🔀 :: (#159) RecruitmentTag Entity 생성

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentInfoListForTeacherVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustom.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/RecruitmentInfoListForTeacherRequest.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/RecruitmentInfoListForTeacherResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#162) VO Refactoring

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/Recruitment.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/hiringarea/HiringArea.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/facade/RecruitmentFacade.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/CreateRecruitmentRequest.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/HiringRepositoryTest.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentTagRepositoryTest.java
=> 🔀 :: (#165) Recruitment, HiringArea 엔티티 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/tag/TagRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/TagController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/TagListResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/TagService.java, src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
=> 🔀 :: (#153) 태그 목록 검색 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/CurrentRecruitmentInfoListForStudentRequest.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#170) 현재 모집 중인 모집의뢰서 목록 API 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustom.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/vo/AllRecruitmentInfoListForStudentVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/vo/CurrentRecruitmentInfoListForStudentVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/AllRecruitmentInfoListForStudentRequest.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/AllRecruitmentInfoListForStudentResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java, src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
=> 🔀 :: (#157) 모든 모집의뢰서 목록 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustom.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/programminglanguage/ProgrammingLanguageRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/screeningprocess/ScreeningProcessRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/tag/TagRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/technology/TechnologyRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/vo/RecruitmentDetailVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/welfare/WelfareRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/RecruitmentDetailResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java, src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
=> 🔀 :: (#156) 모집의뢰서 상세보기 API

src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/Enterprise.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryCustom.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/EnterpriseRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/businessarea/BusinessAreaRepository.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/domain/region/RegionRepository.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/exceptions/EnterpriseErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/exceptions/EnterpriseNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/exceptions/RegionNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/request/ModifyEnterpriseInfoRequest.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/request/RegisterEnterpriseRequest.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java, src/test/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseServiceTest.java, src/test/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentTagRepositoryTest.java
=> 🔀 :: (#167) 기업 등록 API 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/vo/AllRecruitmentInfoListForStudentVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/vo/CurrentRecruitmentInfoListForStudentVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/RecruitmentInfoListForTeacherRequest.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/AllRecruitmentInfoListForStudentResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/CurrentRecruitmentInfoListForStudentResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/RecruitmentDetailResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/RecruitmentInfoListForTeacherResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#176) 메소드들들 살짝 리팩토링

src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/EnterpriseController.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/presentation/payload/response/EnterpriseInfoResponse.java, src/main/java/com/jobits/dsm/benecia/domain/enterprise/service/EnterpriseService.java
=> 🔀 :: (#181) 기업 정보 조회 API 수정

src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepository.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepositoryCustom.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/vo/StudentCurrentStatusVO.java, src/main/java/com/jobits/dsm/benecia/domain/student/exceptions/StudentErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/student/exceptions/StudentNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/student/facade/StudentFacade.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/StudentController.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/payload/response/StudentCurrentStatusResponse.java, src/main/java/com/jobits/dsm/benecia/domain/student/service/StudentService.java
close #158 
학생 로그인 만든 다음 추가 수정할게요
=> 🔀 :: (#158) 현재 사용자 상태 조회 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/Recruitment.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/vo/RecruitmentDetailVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/RecruitmentDetailResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#184) 모집의뢰 상세보기 API 수정

src/main/java/com/jobits/dsm/benecia/domain/review/domain/Review.java, src/main/java/com/jobits/dsm/benecia/domain/review/presentation/ReviewController.java, src/main/java/com/jobits/dsm/benecia/domain/review/service/ReviewService.java, src/test/java/com/jobits/dsm/benecia/domain/review/domain/ReviewRepositoryTest.java
=> 🔀 :: (#191) 후기 엔티티 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/vo/RecruitmentDetailVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/RecruitmentDetailResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#193) 모집의뢰 상세보기 수정

src/main/java/com/jobits/dsm/benecia/domain/application/domain/Application.java, src/main/java/com/jobits/dsm/benecia/domain/review/domain/Review.java
=> 🔀 :: (#197) 외래키 컬럼명 추가

src/main/java/com/jobits/dsm/benecia/domain/application/domain/Application.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/ApplicationAttachment.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/ApplicationAttachmentRepository.java, src/main/java/com/jobits/dsm/benecia/domain/application/presentation/ApplicationController.java, src/main/java/com/jobits/dsm/benecia/domain/application/presentation/payload/request/ApplyEnterpriseRequest.java, src/main/java/com/jobits/dsm/benecia/domain/application/service/ApplicationService.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/exceptions/HiringAreaNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/exceptions/RecruitmentErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/exceptions/RecruitmentNotFoundException.java
=> 🔀 :: (#195) 기업 지원 API

src/main/java/com/jobits/dsm/benecia/domain/review/exceptions/ReviewErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/review/exceptions/ReviewNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/review/presentation/ReviewController.java, src/main/java/com/jobits/dsm/benecia/domain/review/service/ReviewService.java
=> 🔀 :: (#199) 기업 후기 삭제 API

src/main/java/com/jobits/dsm/benecia/domain/review/domain/Review.java, src/main/java/com/jobits/dsm/benecia/domain/review/presentation/ReviewController.java, src/main/java/com/jobits/dsm/benecia/domain/review/presentation/payload/request/ReviseEnterpriseReviewRequest.java, src/main/java/com/jobits/dsm/benecia/domain/review/service/ReviewService.java
=> 🔀 :: (#201) 기업 후기 수정 API

src/main/java/com/jobits/dsm/benecia/domain/review/domain/Review.java, src/main/java/com/jobits/dsm/benecia/domain/review/presentation/ReviewController.java, src/main/java/com/jobits/dsm/benecia/domain/review/service/ReviewService.java
=> 🔀 :: (#203) 기업 후기 확인 API - 산학협력부용

src/main/java/com/jobits/dsm/benecia/domain/review/domain/ReviewRepository.java, src/main/java/com/jobits/dsm/benecia/domain/review/presentation/payload/request/RegisterTrainingReviewRequest.java, src/main/java/com/jobits/dsm/benecia/domain/review/service/ReviewService.java
=> 🔀 :: (#204) 기업 후기 조회 API 수정

src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java, src/main/java/com/jobits/dsm/benecia/global/security/WebConfig.java
=> 🔀 :: (#207) cors

src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/SimilarRecruitmentInfoListForStudentRequest.java
=> 🔀 :: (#211) 비슷한 모집의뢰서 목록 API 수정

src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/CreateRecruitmentRequest.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/RecruitmentDetailResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/SimilarRecruitmentInfoListForStudentResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#213) 변수명 통일

src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepository.java, src/main/java/com/jobits/dsm/benecia/domain/student/exceptions/DepartmentNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/student/exceptions/StudentErrorCode.java, src/main/java/com/jobits/dsm/benecia/domain/student/exceptions/StudentNotFoundException.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/StudentController.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/payload/response/DepartmentStudentListResponse.java, src/main/java/com/jobits/dsm/benecia/domain/student/service/StudentService.java, src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
=> 215 학과 학생 목록 API

src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/StudentController.java, src/main/java/com/jobits/dsm/benecia/domain/student/service/StudentService.java, src/main/java/com/jobits/dsm/benecia/global/security/SecurityConfig.java
=> 216 학생 취업 상태 변경 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/hiringarea/HiringAreaRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/programminglanguage/ProgrammingLanguageRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/screeningprocess/ScreeningProcessRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/tag/RecruitmentTagRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/technology/TechnologyRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/welfare/WelfareRepository.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/facade/RecruitmentFacade.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/request/ModifyRecruitmentRequest.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#221) 모집의뢰 수정 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/RecruitmentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/domain/vo/RecruitmentInfoListForTeacherVO.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/RecruitmentInfoListForTeacherResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#223) 모집의뢰 목록 반환값 추가

src/main/java/com/jobits/dsm/benecia/domain/application/domain/Application.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/ApplicationAttachmentRepository.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/ApplicationRepository.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/ApplicationRepositoryCustom.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/ApplicationRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/application/domain/vo/QueryApplicantListVO.java, src/main/java/com/jobits/dsm/benecia/domain/application/presentation/ApplicationController.java, src/main/java/com/jobits/dsm/benecia/domain/application/service/ApplicationService.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/RecruitmentController.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/QueryApplicantListResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#224) 지원자 목록 조회 API

src/main/java/com/jobits/dsm/benecia/domain/recruitment/presentation/payload/response/AllRecruitmentInfoListForStudentResponse.java, src/main/java/com/jobits/dsm/benecia/domain/recruitment/service/RecruitmentService.java
=> 🔀 :: (#225) 모든 모집의뢰서 API 반환값 추가 - 학생용

src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepositoryCustom.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/StudentRepositoryCustomImpl.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/vo/SearchStudentListVO.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/StudentController.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/payload/response/SearchStudentListResponse.java, src/main/java/com/jobits/dsm/benecia/domain/student/service/StudentService.java
=> 🔀 :: (#231) 학생 검색 API - 산학협력부용

src/main/java/com/jobits/dsm/benecia/domain/student/code/DepartmentCode.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/Department.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/DepartmentRepository.java, src/main/java/com/jobits/dsm/benecia/domain/student/domain/Student.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/StudentCodeController.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/StudentController.java, src/main/java/com/jobits/dsm/benecia/domain/student/presentation/payload/response/DepartmentInformationListResponse.java, src/main/java/com/jobits/dsm/benecia/domain/student/service/StudentCodeService.java, src/main/java/com/jobits/dsm/benecia/domain/student/service/StudentService.java
=> 🔀 :: (#233) code converter 추가
